name: CI

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: build
        run: |
          yarn
          yarn compile
          yarn test
