name: stale

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch: {}

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    if: github.repository == 'mistic100/Photo-Sphere-Viewer'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v5
        with:
          any-of-labels: 'invalid,info requested'
          stale-issue-label: wontfix
          days-before-stale: 7
          days-before-close: 7
          stale-issue-message: |
            This issue has been automatically marked as wontfix because not enough information was provided. It will be closed if no further activity occurs.
